export const BUILTIN_CHANNELS = [

  // NEWS
  { id:1,  name:"Al Jazeera English",  group:"News", country:"🇶🇦", logo:"https://logo.clearbit.com/aljazeera.com",  color:"#c8a84b", url:"https://live-hls-web-aje.getaj.net/AJE/index.m3u8", desc:"Breaking news and in-depth analysis from around the globe." },
  { id:2,  name:"France 24 English",   group:"News", country:"🇫🇷", logo:"https://logo.clearbit.com/france24.com",  color:"#005baa", url:"https://stream.france24.com/hls/live/2037201/F24_EN_HI_HLS/master.m3u8", desc:"International news 24/7 from Paris." },
  { id:3,  name:"DW News",             group:"News", country:"🇩🇪", logo:"https://logo.clearbit.com/dw.com",   color:"#001c56", url:"https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8", desc:"Germany's international broadcaster." },
  { id:4,  name:"NHK World Japan",     group:"News", country:"🇯🇵", logo:"https://logo.clearbit.com/nhk.or.jp",  color:"#c8102e", url:"https://nhkworldlive-lh.akamaihd.net/i/nhkworld_1@189050/master.m3u8", desc:"Japan's public broadcaster, global service." },
  { id:5,  name:"France 24 French",    group:"News", country:"🇫🇷", logo:"https://logo.clearbit.com/france24.com",  color:"#005baa", url:"https://stream.france24.com/hls/live/2037199/F24_FR_HI_HLS/master.m3u8", desc:"Les actualités 24h/24 depuis Paris." },
  { id:6,  name:"TRT World",           group:"News", country:"🇹🇷", logo:"https://logo.clearbit.com/trtworld.com",  color:"#e30613", url:"https://trtworld.live.trt.com.tr/master.m3u8", desc:"Turkey's global news network." },
  { id:7,  name:"CGTN English",        group:"News", country:"🇨🇳", logo:"https://logo.clearbit.com/cgtn.com", color:"#cc0000", url:"https://news.cgtn.com/resource/live/english/cgtn-news.m3u8", desc:"China Global Television Network." },
  { id:8,  name:"Euronews English",    group:"News", country:"🇪🇺", logo:"https://logo.clearbit.com/euronews.com",   color:"#003399", url:"https://euronews-euronews-1-eu.samsung.wurl.tv/manifest/playlist.m3u8", desc:"Pan-European news service." },
  { id:9,  name:"France 24 Arabic",    group:"News", country:"🇫🇷", logo:"https://logo.clearbit.com/france24.com",  color:"#005baa", url:"https://stream.france24.com/hls/live/2037200/F24_AR_HI_HLS/master.m3u8", desc:"فرانس 24 بالعربية" },
  { id:10, name:"DW Arabic",           group:"News", country:"🇩🇪", logo:"https://logo.clearbit.com/dw.com",   color:"#001c56", url:"https://dwamdstream105.akamaized.net/hls/live/2015529/dwstream105/index.m3u8", desc:"أخبار دويتشه فيله بالعربية" },
  { id:11, name:"DW Spanish",          group:"News", country:"🇩🇪", logo:"https://logo.clearbit.com/dw.com",   color:"#001c56", url:"https://dwamdstream103.akamaized.net/hls/live/2015526/dwstream103/index.m3u8", desc:"Noticias de Alemania para el mundo." },
  { id:12, name:"DW Hindi",            group:"News", country:"🇩🇪", logo:"https://logo.clearbit.com/dw.com",   color:"#001c56", url:"https://dwamdstream104.akamaized.net/hls/live/2015527/dwstream104/index.m3u8", desc:"Deutsche Welle Hindi service." },
  { id:13, name:"VOA News",            group:"News", country:"🇺🇸", logo:"https://logo.clearbit.com/voanews.com",  color:"#00205b", url:"", desc:"Voice of America." },
  { id:14, name:"CNA International",  group:"News", country:"🇸🇬", logo:"https://logo.clearbit.com/channelnewsasia.com",  color:"#e30613", url:"https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43eaa09e17df1b195536/index.m3u8", desc:"Channel NewsAsia." },
  { id:15, name:"Africanews English",  group:"News", country:"🌍", logo:"https://logo.clearbit.com/africanews.com",   color:"#ff6b00", url:"https://africanews-africanews-1-eu.samsung.wurl.tv/manifest/playlist.m3u8", desc:"Africa's first English news channel." },
  { id:16, name:"KBS World",           group:"News", country:"🇰🇷", logo:"https://logo.clearbit.com/kbs.co.kr",  color:"#003087", url:"https://kbsworld-lh.akamaihd.net/i/kbsworld_1@303961/master.m3u8", desc:"Korea Broadcasting System World." },
  { id:17, name:"Arise News",          group:"News", country:"🇳🇬", logo:"https://logo.clearbit.com/arise.tv",  color:"#001f5b", url:"", desc:"Africa's global news voice." },
  { id:18, name:"Channels TV Nigeria", group:"News", country:"🇳🇬", logo:"https://logo.clearbit.com/channelstv.com",   color:"#008751", url:"", desc:"Nigeria's number one television station." },
  { id:19, name:"SABC News",           group:"News", country:"🇿🇦", logo:"https://logo.clearbit.com/sabc.co.za", color:"#007a4d", url:"", desc:"South Africa's public broadcaster." },
  { id:20, name:"RT English",          group:"News", country:"🇷🇺", logo:"https://logo.clearbit.com/rt.com",   color:"#1c1c1c", url:"", desc:"News from a Russian international perspective." },

  // SPORTS
  { id:21, name:"Eurosport 1",         group:"Sports", country:"🇪🇺", logo:"https://logo.clearbit.com/eurosport.com", color:"#e4002b", url:"", desc:"Europe's leading multi-sport channel." },
  { id:22, name:"Eurosport 2",         group:"Sports", country:"🇪🇺", logo:"https://logo.clearbit.com/eurosport.com", color:"#e4002b", url:"", desc:"More sport, more often across Europe." },
  { id:23, name:"beIN Sports 1",       group:"Sports", country:"🇶🇦", logo:"https://logo.clearbit.com/beinsports.com", color:"#8b1a7e", url:"", desc:"Premium sport from the Middle East." },
  { id:24, name:"beIN Sports 2",       group:"Sports", country:"🇶🇦", logo:"https://logo.clearbit.com/beinsports.com", color:"#8b1a7e", url:"", desc:"More premium sport from beIN." },
  { id:25, name:"Sky Sports News",     group:"Sports", country:"🇬🇧", logo:"https://logo.clearbit.com/skysports.com", color:"#0072ce", url:"", desc:"The UK's number one sports news channel." },
  { id:26, name:"Fox Sports 1",        group:"Sports", country:"🇺🇸", logo:"https://logo.clearbit.com/foxsports.com", color:"#003DA5", url:"", desc:"America's premier live sports network." },
  { id:27, name:"ESPN",                group:"Sports", country:"🇺🇸", logo:"https://logo.clearbit.com/espn.com", color:"#cc0000", url:"", desc:"The worldwide leader in sports." },
  { id:28, name:"DAZN",               group:"Sports", country:"🌍", logo:"https://logo.clearbit.com/dazn.com", color:"#f5a623", url:"", desc:"Stream live sports on demand." },
  { id:29, name:"SuperSport 1",        group:"Sports", country:"🇿🇦", logo:"https://logo.clearbit.com/supersport.com", color:"#005288", url:"", desc:"South Africa's top sports channel." },
  { id:30, name:"SuperSport Football", group:"Sports", country:"🇿🇦", logo:"https://logo.clearbit.com/supersport.com", color:"#005288", url:"", desc:"Football from Africa and beyond." },
  { id:31, name:"NBA TV",              group:"Sports", country:"🇺🇸", logo:"https://logo.clearbit.com/nba.com", color:"#17408b", url:"", desc:"The official NBA channel." },
  { id:32, name:"NFL Network",         group:"Sports", country:"🇺🇸", logo:"https://logo.clearbit.com/nfl.com", color:"#013369", url:"", desc:"Official NFL broadcast network." },
  { id:33, name:"Tennis Channel",      group:"Sports", country:"🇺🇸", logo:"https://logo.clearbit.com/tennischannel.com",  color:"#006341", url:"", desc:"24/7 tennis coverage worldwide." },
  { id:34, name:"Golf Channel",        group:"Sports", country:"🇺🇸", logo:"https://logo.clearbit.com/golfchannel.com", color:"#006341", url:"", desc:"All golf, all the time." },
  { id:35, name:"Olympic Channel",     group:"Sports", country:"🌍", logo:"https://logo.clearbit.com/olympics.com", color:"#0081c8", url:"", desc:"Celebrating the Olympic movement." },
  { id:36, name:"Fight Network",       group:"Sports", country:"🇺🇸", logo:"https://logo.clearbit.com/fightnetwork.com",  color:"#c8102e", url:"", desc:"MMA and combat sports." },
  { id:37, name:"Gol TV",              group:"Sports", country:"🇺🇸", logo:"https://logo.clearbit.com/goltv.tv", color:"#006341", url:"", desc:"The soccer channel for the Americas." },
  { id:38, name:"SporTV",              group:"Sports", country:"🇧🇷", logo:"https://logo.clearbit.com/sportv.globo.com", color:"#005288", url:"", desc:"Brazil's sports broadcasting leader." },

  // ENTERTAINMENT
  { id:39, name:"MTV",                 group:"Entertainment", country:"🌍", logo:"https://logo.clearbit.com/mtv.com",  color:"#000", url:"", desc:"Music television around the clock." },
  { id:40, name:"Comedy Central",      group:"Entertainment", country:"🇺🇸", logo:"https://logo.clearbit.com/comedycentral.com", color:"#ffde00", url:"", desc:"Stand-up, shows, and laughs all day." },
  { id:41, name:"National Geographic", group:"Entertainment", country:"🌍", logo:"https://logo.clearbit.com/nationalgeographic.com", color:"#ffcc00", url:"", desc:"Explore the planet like never before." },
  { id:42, name:"Discovery Channel",   group:"Entertainment", country:"🌍", logo:"https://logo.clearbit.com/discovery.com", color:"#005288", url:"", desc:"Science, history, and adventure." },
  { id:43, name:"History Channel",     group:"Entertainment", country:"🇺🇸", logo:"https://logo.clearbit.com/history.com", color:"#8b6914", url:"", desc:"History brought to life." },
  { id:44, name:"BBC Earth",           group:"Entertainment", country:"🇬🇧", logo:"https://logo.clearbit.com/bbc.co.uk", color:"#006a4e", url:"", desc:"Stunning nature documentaries." },
  { id:45, name:"TLC",                 group:"Entertainment", country:"🇺🇸", logo:"https://logo.clearbit.com/tlc.com", color:"#e30613", url:"", desc:"Reality TV." },
  { id:46, name:"A&E",                 group:"Entertainment", country:"🇺🇸", logo:"https://logo.clearbit.com/aetv.com", color:"#000", url:"", desc:"Arts, entertainment, and real-life stories." },
  { id:47, name:"E! Entertainment",   group:"Entertainment", country:"🇺🇸", logo:"https://logo.clearbit.com/eonline.com", color:"#ff69b4", url:"", desc:"Celebrity news and pop culture." },
  { id:48, name:"Bravo",               group:"Entertainment", country:"🇺🇸", logo:"https://logo.clearbit.com/bravotv.com", color:"#000", url:"", desc:"Reality TV and lifestyle." },
  { id:49, name:"FX",                  group:"Entertainment", country:"🇺🇸", logo:"https://logo.clearbit.com/fxnetworks.com", color:"#000", url:"", desc:"Critically acclaimed drama and comedy." },
  { id:50, name:"AMC",                 group:"Entertainment", country:"🇺🇸", logo:"https://logo.clearbit.com/amc.com", color:"#c8a84b", url:"", desc:"Story-driven TV." },
  { id:51, name:"ITV",                 group:"Entertainment", country:"🇬🇧", logo:"https://logo.clearbit.com/itv.com", color:"#f5a623", url:"", desc:"UK's flagship commercial broadcaster." },
  { id:52, name:"Channel 4 UK",        group:"Entertainment", country:"🇬🇧", logo:"https://logo.clearbit.com/channel4.com", color:"#000", url:"", desc:"Bold, alternative British TV." },
  { id:53, name:"RTL Germany",         group:"Entertainment", country:"🇩🇪", logo:"https://logo.clearbit.com/rtl.de", color:"#cc0000", url:"", desc:"Germany's most-watched private channel." },
  { id:54, name:"Sony Entertainment",  group:"Entertainment", country:"🇮🇳", logo:"https://logo.clearbit.com/sonyliv.com",  color:"#005288", url:"", desc:"India's premier entertainment channel." },
  { id:55, name:"Zee TV",              group:"Entertainment", country:"🇮🇳", logo:"https://logo.clearbit.com/zee5.com", color:"#cc0000", url:"", desc:"India's top Hindi entertainment." },
  { id:56, name:"Star Plus",           group:"Entertainment", country:"🇮🇳", logo:"https://logo.clearbit.com/hotstar.com", color:"#cc0000", url:"", desc:"India's number one channel." },

  // MOVIES
  { id:57, name:"TCM Classic Movies",  group:"Movies", country:"🇺🇸", logo:"https://logo.clearbit.com/tcm.com", color:"#c8a84b", url:"", desc:"The greatest films ever made." },
  { id:58, name:"Film4 UK",            group:"Movies", country:"🇬🇧", logo:"https://logo.clearbit.com/channel4.com", color:"#e4002b", url:"", desc:"British and world cinema, free to air." },
  { id:59, name:"Sundance TV",         group:"Movies", country:"🇺🇸", logo:"https://logo.clearbit.com/sundancetv.com", color:"#ff6b00", url:"", desc:"Independent film and drama." },
  { id:60, name:"MGM HD",              group:"Movies", country:"🇺🇸", logo:"https://logo.clearbit.com/mgm.com", color:"#c8a84b", url:"", desc:"Classic MGM titles." },
  { id:61, name:"Starz",               group:"Movies", country:"🇺🇸", logo:"https://logo.clearbit.com/starz.com", color:"#003DA5", url:"", desc:"Premium movies and originals." },
  { id:62, name:"Showtime",            group:"Movies", country:"🇺🇸", logo:"https://logo.clearbit.com/showtime.com", color:"#cc0000", url:"", desc:"Award-winning series and movies." },
  { id:63, name:"Paramount Network",   group:"Movies", country:"🇺🇸", logo:"https://logo.clearbit.com/paramount.com", color:"#003DA5", url:"", desc:"Mountains of entertainment." },
  { id:64, name:"Fox Movies",          group:"Movies", country:"🌍", logo:"https://logo.clearbit.com/foxmovies.com",  color:"#003DA5", url:"", desc:"Blockbuster Fox films 24/7." },
  { id:65, name:"Universal Channel",   group:"Movies", country:"🌍", logo:"https://logo.clearbit.com/universalpictures.com", color:"#005288", url:"", desc:"Universal Pictures classics." },
  { id:66, name:"Sony Movies",         group:"Movies", country:"🌍", logo:"https://logo.clearbit.com/sonypictures.com",  color:"#005288", url:"", desc:"Sony Pictures film library." },
  { id:67, name:"Warner TV",           group:"Movies", country:"🌍", logo:"https://logo.clearbit.com/warnerbros.com", color:"#005288", url:"", desc:"Warner Bros. classics." },
  { id:68, name:"Movies24 UK",         group:"Movies", country:"🇬🇧", logo:"M24", color:"#c8a84b", url:"", desc:"Free UK movies channel." },
  { id:69, name:"Sky Cinema",          group:"Movies", country:"🇬🇧", logo:"https://logo.clearbit.com/sky.com", color:"#0072ce", url:"", desc:"Sky's premium movie service." },
  { id:70, name:"Mnet Movies",         group:"Movies", country:"🇿🇦", logo:"https://logo.clearbit.com/mnet.tv", color:"#e30613", url:"", desc:"Africa's premier movie channel." },

  // DOCUMENTARY
  { id:71, name:"NASA TV",             group:"Documentary", country:"🇺🇸", logo:"https://logo.clearbit.com/nasa.gov", color:"#0b3d91", url:"https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8", desc:"Live rocket launches, spacewalks, and space science." },
  { id:72, name:"NASA TV Media",       group:"Documentary", country:"🇺🇸", logo:"https://logo.clearbit.com/nasa.gov", color:"#0b3d91", url:"https://ntv2.akamaized.net/hls/live/2015093/NASA-NTV2-HLS/master.m3u8", desc:"NASA's media channel with press briefings." },
  { id:73, name:"Animal Planet",       group:"Documentary", country:"🌍", logo:"https://logo.clearbit.com/animalplanet.com", color:"#006341", url:"", desc:"The world's most extreme animals." },
  { id:74, name:"Smithsonian Channel", group:"Documentary", country:"🇺🇸", logo:"https://logo.clearbit.com/smithsonianchannel.com", color:"#8b6914", url:"", desc:"Real stories from history and science." },
  { id:75, name:"Nat Geo Wild",        group:"Documentary", country:"🌍", logo:"https://logo.clearbit.com/nationalgeographic.com", color:"#ffcc00", url:"", desc:"The most extreme wildlife on Earth." },
  { id:76, name:"Science Channel",     group:"Documentary", country:"🇺🇸", logo:"https://logo.clearbit.com/sciencechannel.com", color:"#005288", url:"", desc:"Question everything." },
  { id:77, name:"PBS America",         group:"Documentary", country:"🇺🇸", logo:"https://logo.clearbit.com/pbs.org", color:"#005288", url:"", desc:"America's trusted public broadcaster." },
  { id:78, name:"BBC Four",            group:"Documentary", country:"🇬🇧", logo:"https://logo.clearbit.com/bbc.co.uk", color:"#cc0000", url:"", desc:"Arts and documentaries." },
  { id:79, name:"Arte",                group:"Documentary", country:"🇫🇷", logo:"https://logo.clearbit.com/arte.tv", color:"#e30613", url:"", desc:"European culture and arts." },
  { id:80, name:"Travel Channel",      group:"Documentary", country:"🇺🇸", logo:"https://logo.clearbit.com/travelchannel.com", color:"#ff6b00", url:"", desc:"Adventures from around the world." },
  { id:81, name:"Food Network",        group:"Documentary", country:"🇺🇸", logo:"https://logo.clearbit.com/foodnetwork.com", color:"#ff6b00", url:"", desc:"Cooking shows and food competitions." },
  { id:82, name:"Military Channel",    group:"Documentary", country:"🇺🇸", logo:"https://logo.clearbit.com/military.com", color:"#556b2f", url:"", desc:"Military history and operations." },

  // KIDS
  { id:83, name:"Cartoon Network",        group:"Kids", country:"🇺🇸", logo:"https://logo.clearbit.com/cartoonnetwork.com", color:"#000", url:"", desc:"The best cartoons for kids and families." },
  { id:84, name:"Boomerang",              group:"Kids", country:"🌍", logo:"https://logo.clearbit.com/boomerang.com", color:"#ff6200", url:"", desc:"Classic cartoons you grew up with." },
  { id:85, name:"Nickelodeon",            group:"Kids", country:"🇺🇸", logo:"https://logo.clearbit.com/nick.com", color:"#f58220", url:"", desc:"The kids channel that never sleeps." },
  { id:86, name:"Nick Jr.",               group:"Kids", country:"🇺🇸", logo:"https://logo.clearbit.com/nickjr.com", color:"#f58220", url:"", desc:"Preschool cartoons and learning." },
  { id:87, name:"Disney Channel",         group:"Kids", country:"🌍", logo:"https://logo.clearbit.com/disneychannel.com", color:"#003DA5", url:"", desc:"Family entertainment from Disney." },
  { id:88, name:"Disney Junior",          group:"Kids", country:"🌍", logo:"https://logo.clearbit.com/disneyjunior.com", color:"#003DA5", url:"", desc:"Disney for the youngest viewers." },
  { id:89, name:"CBBC",                   group:"Kids", country:"🇬🇧", logo:"https://logo.clearbit.com/bbc.co.uk", color:"#006400", url:"", desc:"BBC's channel for 6-12 year olds." },
  { id:90, name:"CBeebies",               group:"Kids", country:"🇬🇧", logo:"https://logo.clearbit.com/bbc.co.uk", color:"#ff6b00", url:"", desc:"BBC for preschoolers." },
  { id:91, name:"Baby TV",                group:"Kids", country:"🌍", logo:"https://logo.clearbit.com/babytv.com", color:"#ff69b4", url:"", desc:"Programming for the very youngest." },
  { id:92, name:"Cartoon Network Arabic", group:"Kids", country:"🇦🇪", logo:"https://logo.clearbit.com/cartoonnetwork.com", color:"#000", url:"", desc:"Cartoons in Arabic." },
  { id:93, name:"Spacetoon",              group:"Kids", country:"🇦🇪", logo:"https://logo.clearbit.com/spacetoon.com", color:"#3d85c8", url:"", desc:"Arab world's leading kids channel." },
  { id:94, name:"Super RTL",              group:"Kids", country:"🇩🇪", logo:"https://logo.clearbit.com/superrtl.de", color:"#ff6b00", url:"", desc:"Germany's top children's channel." },

  // MUSIC
  { id:95,  name:"VH1",         group:"Music", country:"🇺🇸", logo:"https://logo.clearbit.com/vh1.com", color:"#ff1744", url:"", desc:"Pop culture and music videos 24/7." },
  { id:96,  name:"Mezzo Live",  group:"Music", country:"🇫🇷", logo:"https://logo.clearbit.com/mezzo.tv",  color:"#1a237e", url:"", desc:"Classical music and jazz in HD." },
  { id:97,  name:"Club MTV",    group:"Music", country:"🌍", logo:"https://logo.clearbit.com/mtv.com", color:"#000",    url:"", desc:"The hottest club and dance music." },
  { id:98,  name:"MTV Hits",    group:"Music", country:"🌍", logo:"https://logo.clearbit.com/mtv.com", color:"#000",    url:"", desc:"The biggest chart hits." },
  { id:99,  name:"MTV Base",    group:"Music", country:"🌍", logo:"https://logo.clearbit.com/mtv.com", color:"#000",    url:"", desc:"Hip-hop, R&B, and urban music." },
  { id:100, name:"Trace Urban", group:"Music", country:"🌍", logo:"https://logo.clearbit.com/trace.tv",  color:"#ff6b00", url:"", desc:"Urban music across Africa and beyond." },
  { id:101, name:"Trace Africa",group:"Music", country:"🌍", logo:"https://logo.clearbit.com/trace.tv",  color:"#ff6b00", url:"", desc:"Africa's music, Africa's stories." },
  { id:102, name:"BET Music",   group:"Music", country:"🇺🇸", logo:"https://logo.clearbit.com/bet.com", color:"#ff6b00", url:"", desc:"Black entertainment and music." },
  { id:103, name:"Jazz TV",     group:"Music", country:"🌍", logo:"https://logo.clearbit.com/jazztv.fr",  color:"#1a1a2e", url:"", desc:"Jazz 24 hours a day." },
  { id:104, name:"4Music UK",   group:"Music", country:"🇬🇧", logo:"https://logo.clearbit.com/4music.com",   color:"#000",    url:"", desc:"The UK's freshest music channel." },
  { id:105, name:"Kerrang! TV", group:"Music", country:"🇬🇧", logo:"https://logo.clearbit.com/kerrang.com",  color:"#000",    url:"", desc:"Rock and metal 24/7." },

  // LIFESTYLE
  { id:106, name:"HGTV",                   group:"Lifestyle", country:"🇺🇸", logo:"https://logo.clearbit.com/hgtv.com", color:"#006341", url:"", desc:"Home and garden TV." },
  { id:107, name:"Food Network Lifestyle",  group:"Lifestyle", country:"🇺🇸", logo:"https://logo.clearbit.com/foodnetwork.com", color:"#ff6b00", url:"", desc:"All recipes, all the time." },
  { id:108, name:"Fashion TV",              group:"Lifestyle", country:"🌍", logo:"https://logo.clearbit.com/fashion.tv", color:"#000", url:"https://www.fashion.tv/live/stream2/playlist.m3u8", desc:"The world's only 24/7 fashion channel." },
  { id:109, name:"Fine Living",             group:"Lifestyle", country:"🌍", logo:"https://logo.clearbit.com/fineliving.com",   color:"#c8a84b", url:"", desc:"Luxury, travel, and good living." },
  { id:110, name:"Style Network",           group:"Lifestyle", country:"🇺🇸", logo:"https://logo.clearbit.com/styleseat.com",  color:"#ff69b4", url:"", desc:"Fashion, beauty, and design." },
];

export const CATEGORIES = ["All", ...new Set(BUILTIN_CHANNELS.map(c => c.group))];

export const getFeatured = () => BUILTIN_CHANNELS.find(c => c.url) || BUILTIN_CHANNELS[0];